env = Environment(CPPPATH='include')

c_srcs = [
#	'App/Looper.cpp',
	'App/Message.cpp',

#	'Support/Autolock.cpp',
	'Support/Archivable.cpp',
	'Support/DataIO.cpp',
	'Support/BufferIO.cpp',
	'Support/BlockCache.cpp',
	'Support/Flattenable.cpp',
	'Support/List.cpp',
	'Support/Locker.cpp',
	'Support/StopWatch.cpp',
	'Support/String.cpp',

#	'Storage/EntryList.cpp',
	'Storage/Entry.cpp',
	'Storage/Node.cpp',
	'Storage/Statable.cpp',
	'Storage/Directory.cpp',
	'Storage/EntryList.cpp',
	'Storage/File.cpp',
	'Storage/Path.cpp',
	'Storage/Volume.cpp'
]

c_objs = env.SharedObject(c_srcs)

Return('c_objs')
