env = Environment(CPPPATH='include')

c_srcs = [
#	'App/Looper.cpp',

#	'Support/Autolock.cpp',
	'Support/Archivable.cpp',
	'Support/DataIO.cpp',
	'Support/BufferIO.cpp',
	'Support/BlockCache.cpp',
	'Support/List.cpp',
#	'Support/Locker.cpp',
	'Support/StopWatch.cpp',
	'Support/String.cpp'

#	'Storage/EntryList.cpp',
#	'Storage/Entry.cpp',
#	'Storage/Statable.cpp'
]

c_objs = env.SharedObject(c_srcs)

Return('c_objs')
