env = Environment(DPATH='.')

d_srcs = [
	'Be/Interface/Point.d',
	'Be/Interface/Rect.d',
	'Be/Interface/Size.d',
	'Be/Interface/Polygon.d',
	'Be/Interface/Region.d',
	'Be/Interface/Alignment.d',
	'Be/Interface/InterfaceDefs.d',
	'Be/Interface/Input.d',

	'Be/App/Application.d',
	'Be/App/Clipboard.d',
	'Be/App/Cursor.d',
	'Be/App/Looper.d',
	'Be/App/Invoker.d',
	'Be/App/Messenger.d',
	'Be/App/Message.d',
	'Be/App/MessageFilter.d',
	'Be/App/MessageQueue.d',
	'Be/App/MessageRunner.d',
	'Be/App/Notification.d',
	'Be/App/Handler.d',
	'Be/App/PropertyInfo.d',
	'Be/App/Roster.d',

	'Be/Kernel/OS.d',

	'Be/Storage/StorageDefs.d',
	'Be/Storage/File.d',
	'Be/Storage/Path.d',
	'Be/Storage/Directory.d',
	'Be/Storage/Statable.d',
	'Be/Storage/Node.d',
	'Be/Storage/Entry.d',
	'Be/Storage/EntryList.d',
	'Be/Storage/Volume.d',
	'Be/Storage/VolumeRoster.d',
	'Be/Storage/FindDirectory.d',

	'Be/Support/Archivable.d',
#	'Be/Support/Autolock.d',
	'Be/Support/DataIO.d',
	'Be/Support/BufferIO.d',
	'Be/Support/BlockCache.d',
	'Be/Support/BObject.d',
	'Be/Support/Flattenable.d',
	'Be/Support/List.d',
	'Be/Support/Locker.d',
	'Be/Support/StopWatch.d',
	'Be/Support/String.d',
	'Be/Support/SupportDefs.d',
	'Be/Support/types.d',
	'Be/Support/Errors.d',
	'Be/Support/HelperFunctions.d'
]

d_objs = env.SharedObject(d_srcs)

Return('d_objs')
