env = Environment(DPATH='.')

d_srcs = [
#	'App/Looper.d',
	'App/Message.d',
#	'Kernel/OS.d',

	'Storage/StorageDefs.d',

	'Support/Archivable.d',
#	'Support/Autolock.d',
	'Support/DataIO.d',
	'Support/BufferIO.d',
	'Support/BlockCache.d',
#	'Support/BObject.d',
	'Support/Flattenable.d',
	'Support/List.d',
	'Support/Locker.d',
	'Support/StopWatch.d',
	'Support/String.d',
	'Support/SupportDefs.d',
	'Support/types.d'
]

d_objs = env.SharedObject(d_srcs)

Return('d_objs')
